services:
    Overblog\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor:
        class: Overblog\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor
        public: false
        tags:
            - { name: overblog_graphql.definition_config_processor, priority: 2048 }

    Overblog\GraphQLBundle\Definition\ConfigProcessor\InjectServicesConfigProcessor:
        class: Overblog\GraphQLBundle\Definition\ConfigProcessor\InjectServicesConfigProcessor
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: overblog_graphql.definition_config_processor, priority: 1024 }

    Overblog\GraphQLBundle\Definition\ConfigProcessor\AclConfigProcessor:
        class: Overblog\GraphQLBundle\Definition\ConfigProcessor\AclConfigProcessor
        arguments:
            - '@overblog_graphql.access_resolver'
            - "%overblog_graphql.default_resolver%"
        public: false
        tags:
            - { name: overblog_graphql.definition_config_processor }
