services:
    #relay
    overblog_graphql.definition.relay_mutation_mutation_field:
        class:  Overblog\GraphQLBundle\Relay\Mutation\MutationField
        tags:
            - { name: overblog_graphql.field, alias: Mutation }

    overblog_graphql.definition.relay_node_global_id_field:
        class:  Overblog\GraphQLBundle\Relay\Node\GlobalIdField
        tags:
            - { name: overblog_graphql.field, alias: GlobalId }

    overblog_graphql.definition.relay_node_raw_id_field:
        class:  Overblog\GraphQLBundle\Relay\Node\RawIdField
        tags:
            - { name: overblog_graphql.field, alias: RawId }

    overblog_graphql.definition.relay_node_node_field:
        class:  Overblog\GraphQLBundle\Relay\Node\NodeField
        tags:
            - { name: overblog_graphql.field, alias: Node }

    overblog_graphql.definition.relay_node_plurial_identifying_root_field:
        class:  Overblog\GraphQLBundle\Relay\Node\PluralIdentifyingRootField
        tags:
            - { name: overblog_graphql.field, alias: PluralIdentifyingRoot }
