services:
    #relay
    overblog_graphql.definition.relay_forward_connection_arg:
        class:  Overblog\GraphQLBundle\Relay\Connection\ForwardConnectionArgs
        tags:
            - { name: overblog_graphql.arg, alias: ForwardConnectionArgs }

    overblog_graphql.definition.relay_backward_connection_arg:
        class:  Overblog\GraphQLBundle\Relay\Connection\BackwardConnectionArgs
        tags:
            - { name: overblog_graphql.arg, alias: BackwardConnectionArgs }

    overblog_graphql.definition.relay_connection_arg:
        class:  Overblog\GraphQLBundle\Relay\Connection\ConnectionArgs
        tags:
            - { name: overblog_graphql.arg, alias: ConnectionArgs }
