services:
    overblog_graph.request_executor:
        class: Overblog\GraphBundle\Request\Executor
        arguments:
            - "@overblog_graph.schema"
            - "@event_dispatcher"

    overblog_graph.request_parser:
        class: Overblog\GraphBundle\Request\Parser

    overblog_graph.schema:
        class: GraphQL\Schema
        public: false
        factory: ["@overblog_graph.schema_builder", create]
        arguments:
            - ~
            - ~

    overblog_graph.schema_builder:
        class: Overblog\GraphBundle\Definition\Builder\SchemaBuilder
        arguments:
            - "@overblog_graph.type_resolver"

    overblog_graph.type_builder:
        class: Overblog\GraphBundle\Definition\Builder\TypeBuilder
        arguments:
            - "@overblog_graph.config_resolver"

    overblog_graph.config_resolver:
        class: Overblog\GraphBundle\Resolver\ConfigResolver
        arguments:
            - "@overblog_graph.type_resolver"
            - "@overblog_graph.field_resolver"
            - "@overblog_graph.expression_language"
            - %kernel.debug%

    overblog_graph.type_resolver:
        class: Overblog\GraphBundle\Resolver\TypeResolver
        arguments:
            - "@service_container"

    overblog_graph.field_resolver:
        class: Overblog\GraphBundle\Resolver\FieldResolver
        arguments:
            - "@service_container"

    overblog_graph.relsover_resolver:
        class: Overblog\GraphBundle\Resolver\ResolverResolver
        arguments:
            - "@service_container"

    overblog_graph.cache_expression_language_parser.default:
        class: Symfony\Component\ExpressionLanguage\ParserCache\ArrayParserCache
        public: false

    overblog_graph.expression_language.default:
        class: Overblog\GraphBundle\ExpressionLanguage\ExpressionLanguage
        public: false
        arguments:
            - "@overblog_graph.cache_expression_language_parser"
        calls:
            - ["setContainer", ["@service_container"]]
