services:
    overblog_graph.request_executor:
        class: Overblog\GraphBundle\Request\Executor
        arguments:
            - "@overblog_graph.schema"

    overblog_graph.request_parser:
        class: Overblog\GraphBundle\Request\Parser

    overblog_graph.schema:
        class: GraphQL\Schema
        public: false
        factory: ["@overblog_graph.schema_builder", create]
        arguments:
            - ~
            - ~

    overblog_graph.schema_builder:
        class: Overblog\GraphBundle\Definition\Builder\SchemaBuilder
        arguments:
            - "@overblog_graph.type_resolver"

    overblog_graph.type_builder:
        class: Overblog\GraphBundle\Definition\Builder\TypeBuilder
        arguments:
            - "@overblog_graph.config_resolver"

    overblog_graph.config_resolver:
        class: Overblog\GraphBundle\Resolver\ConfigResolver
        arguments:
            - "@overblog_graph.type_resolver"
            - "@overblog_graph.expression_language"
            - "@service_container"

    overblog_graph.type_resolver:
        class: Overblog\GraphBundle\Resolver\TypeResolver
        arguments:
            - "@service_container"

    overblog_graph.expression_language:
        class: Overblog\GraphBundle\ExpressionLanguage\ExpressionLanguage
