services:
    overblog_graphql.error_handler:
        class: Overblog\GraphQLBundle\Error\ErrorHandler
        public: false
        arguments:
            - ~
            - "@?logger"

    overblog_graphql.request_executor:
        class: Overblog\GraphQLBundle\Request\Executor
        arguments:
            - "@overblog_graphql.schema"
            - "@event_dispatcher"
            - %kernel.debug%
            - "@overblog_graphql.error_handler"

    overblog_graphql.request_parser:
        class: Overblog\GraphQLBundle\Request\Parser

    overblog_graphql.schema:
        class: GraphQL\Schema
        public: false
        factory: ["@overblog_graphql.schema_builder", create]
        arguments:
            - ~
            - ~
            - ~

    overblog_graphql.schema_builder:
        class: Overblog\GraphQLBundle\Definition\Builder\SchemaBuilder
        public: false
        arguments:
            - "@overblog_graphql.type_resolver"
            - []
            - false

    overblog_graphql.type_builder:
        class: Overblog\GraphQLBundle\Definition\Builder\TypeBuilder
        arguments:
            - "@overblog_graphql.config_resolver"

    overblog_graphql.config_resolver:
        class: Overblog\GraphQLBundle\Resolver\ConfigResolver
        arguments:
            - "@overblog_graphql.type_resolver"
            - "@overblog_graphql.field_resolver"
            - "@overblog_graphql.arg_resolver"
            - "@overblog_graphql.expression_language"

    overblog_graphql.type_resolver:
        class: Overblog\GraphQLBundle\Resolver\TypeResolver
        arguments:
            - "@service_container"

    overblog_graphql.field_resolver:
        class: Overblog\GraphQLBundle\Resolver\FieldResolver
        arguments:
            - "@service_container"

    overblog_graphql.arg_resolver:
        class: Overblog\GraphQLBundle\Resolver\ArgResolver
        arguments:
            - "@service_container"

    overblog_graphql.resolver_resolver:
        class: Overblog\GraphQLBundle\Resolver\ResolverResolver
        arguments:
            - "@service_container"

    overblog_graphql.mutation_resolver:
        class: Overblog\GraphQLBundle\Resolver\MutationResolver
        arguments:
            - "@service_container"

    overblog_graphql.cache_expression_language_parser.default:
        class: Symfony\Component\ExpressionLanguage\ParserCache\ArrayParserCache
        public: false

    overblog_graphql.expression_language.default:
        class: Overblog\GraphQLBundle\ExpressionLanguage\ExpressionLanguage
        public: false
        arguments:
            - "@overblog_graphql.cache_expression_language_parser"
        calls:
            - ["setContainer", ["@service_container"]]

    overblog_graphql.event_listener.request_file_listener:
        class: Overblog\GraphQLBundle\EventListener\RequestFilesListener
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: graphql.executor.context, method: onExecutorContextEvent }
