tools:
    external_code_coverage:
        timeout: 1200
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests-and-coverage:
        tests:
            override:
                - true

filter:
    excluded_paths:
        - "tests/"
